d={}
name=input("Enter name:")
language=input("Enter language:")
d.update({name:language})
name=input("Enter name:")
language=input("Enter language:")
d.update({name:language})
name=input("Enter name:")
language=input("Enter language:")
d.update({name:language})
name=input("Enter name:")
language=input("Enter language:")
d.update({name:language})
name=input("Enter name:")
language=input("Enter language:")
d.update({name:language})
name=input("Enter name:")
language=input("Enter language:")
d.update({name:language})
print(d)

