marks=[]
m1=int(input("Enter student mark 1:"))
marks.append(m1)
m2=int(input("Enter student mark 2:"))
marks.append(m2)
m3=int(input("Enter student mark 3:"))
marks.append(m3)
m4=int(input("Enter student mark 4:"))
marks.append(m4)
m5=int(input("Enter student mark 5:"))
marks.append(m5)
m6=int(input("Enter student mark 6:"))
marks.append(m6)
marks.sort()
print(marks)